# Generated by Django 2.2.3 on 2020-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='endDated',
            field=models.DateTimeField(blank=True),
        ),
    ]
