# Generated by Django 2.2.3 on 2020-05-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20200504_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='endDated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
