# Generated by Django 2.2.3 on 2020-05-07 00:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_activity_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='animals',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
