# Generated by Django 2.2.3 on 2020-05-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_activity_animals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='animals',
            new_name='people',
        ),
    ]
