# Generated by Django 2.2.3 on 2020-05-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20200504_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='minutes',
        ),
    ]
