# Generated by Django 2.2.3 on 2020-05-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20200507_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
