# Generated by Django 2.2.3 on 2020-05-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='activity',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='endDated',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='isCompleted',
            new_name='is_completed',
        ),
    ]
