# Generated by Django 2.2.3 on 2020-05-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20200504_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(null=True, to='challenges.Tag'),
        ),
    ]
