# Generated by Django 2.2.3 on 2020-05-04 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20200504_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='challenge',
            name='modified',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
