# Generated by Django 2.2.3 on 2020-05-04 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20200504_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
