# Generated by Django 2.2.3 on 2020-05-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_auto_20200504_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
